# @package _global_
defaults:
  - /models/causal_model
model:
  hidden_size: 100
  num_layers: 3
  intermediate_size: 400
  num_attention_heads: 4
  causal: true
  model_type: llama
  hidden_act: silu
  token_typing: false
