# @package _global_
defaults:
  - /models/causal_model
model:
  hidden_size: 640
  num_layers: 13
  intermediate_size: 2560
  num_attention_heads: 10
  causal: true
  model_type: llama
  hidden_act: silu
  token_typing: false
