# @package _global_
defaults:
  - /models/causal_model
model:
  hidden_size: 1440
  num_layers: 20
  intermediate_size: 4096
  num_attention_heads: 20
  causal: true
  model_type: llama
  hidden_act: silu
