# @package _global_
defaults:
  - /models/causal_model
model:
  causal: true
  head_dim: 128
  hidden_size: 576
  initializer_range: 0.02
  intermediate_size: 2304
  max_window_layers: 20
  num_attention_heads: 9
  num_layers: 8
  num_key_value_heads: 9
  rms_norm_eps: 1e-06
  rope_scaling: null
  rope_theta: 1000000
  sliding_window: null
  use_sliding_window: false
