# @package _global_
defaults:
  - /data/omol_4M


wandb:
  group_name: Omol
  run_name: 57M_last_only_delta

dataset:
  # If null, use all data. Update for different scaling experiments.
  pipeline_v2: True
  training_percentage: null
  per_atom_target: false
  energy_last: false
  force_last: true
  n_val: 1024
  rotation_augmentation: true
  permutation_augmentation: false
  continuous: true
  n_bins:
    pos: 10
    force: 10
    target: 2048
  joint_embedding: true
  joint_embedding_force: true
  joint_embed_atoms: true
  first_force_only: false
  prior_path_train: null
  prior_path_val: null
  norm_stats_path: data/Omol/train_metadata.npy
  name: omol

  train_dataset:
    _target_: mmlm.datasets_v2.builder.build_dataset
    cfg:
      _target_: mmlm.datasets_v2.config.DatasetV2Cfg
      loader:
        _target_: mmlm.datasets_v2.loaders.omol_loader.OmolLoader
        path: data/Omol/train_4M
      transforms:
        - _target_: mmlm.datasets_v2.core.transforms.RotationTransform
      formatter:
        _target_: mmlm.datasets_v2.core.formatter.AtomFormatter
        finetune: False
      bin_spec_path: data/bins/omol_joint_bins_10_10_2048.npz

  val_dataset:
    _target_: mmlm.datasets_v2.builder.build_dataset
    cfg:
      _target_: mmlm.datasets_v2.config.DatasetV2Cfg
      loader:
        _target_: mmlm.datasets_v2.loaders.omol_loader.OmolLoader
        path: data/Omol/val
      transforms: [] # No augmentations for validation
      formatter:
        _target_: mmlm.datasets_v2.core.formatter.AtomFormatter
        finetune: False
      bin_spec_path: data/bins/omol_joint_bins_10_10_2048.npz
        

training:
  bf16: False
  fp16: True
  # For NERSC, use 8 nodes so 32 GPUs for an effective batch size of 1024
  batch_size: 16
  gradient_accumulation_steps: 2
  lr: 0.0003
  torch_compile: True
  eval_steps: 500
  dataloader_num_workers: 0
  num_epochs: 30
  eval_batch_size: 16
  nan_loss_cutoff: 20
  max_grad_norm: 1
  full_eval: False
  resume_from_checkpoint: True
  attn_implementation: sdpa # Seems to be similar to flash_attention_2 when enabling model_bf16
  model_bf16: False
  eval_accumulation_steps: 4

model:
  model_type: llama_continuous
  loss_weights:
    target: 1
    force: 1
    pos: 1
  loss_name: xent
