name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mmlm
          environment-file: env_simple.yml
          auto-activate-base: false

      - name: Install additional packages
        shell: bash -l {0}
        run: |
          conda activate mmlm
          pip install torch_geometric pytest
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate mmlm
          pytest tests -v
